// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Back.Data.Models;

public partial class Transaccione
{
    public int CodTransaccion { get; set; }

    public int? CantidadTicket { get; set; }

    public DateTime? FechaCompra { get; set; }

    public int? CodPago { get; set; }

    public int? IdEstado { get; set; }

    public int? IdUsuario { get; set; }
    [JsonIgnore]
    public virtual MetodosPago CodPagoNavigation { get; set; }
    [JsonIgnore]
    public virtual Estado IdEstadoNavigation { get; set; }
    [JsonIgnore]
    public virtual Usuario IdUsuarioNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}